# Generated by Django 2.2.2 on 2019-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_available',
        ),
        migrations.AddField(
            model_name='flight',
            name='seats',
            field=models.ManyToManyField(related_name='seats', to='flight.Seat'),
        ),
    ]
