language: python
python:
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls

script:
  - coverage run --source='.' ./manage.py test
  # Code coverage
  - coverage report

after_script:
  - coveralls
